In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
os.chdir("/content/drive/My Drive/dataset")

In [3]:
import pandas as pd

# Read the CSV file
df = pd.read_csv("Final.csv")

# Display the dataframe
print(df)

                                                    title  label
0       'it +0092 s no show for cinepolis now the indi...      2
1       James Corden seducing Jamie Dornan ‘Fifty Shad...      1
2       SARAH PALIN’S SON BREAKS Into Family Home…Sava...      0
3                     Brad Pitt moves in with Kate Hudson      0
4       man removed from flight after allegedly harass...      2
...                                                   ...    ...
155116  First Time in 30 Years: US Deploys B-52 Bomber...      0
155117  North Korea preparing long-range missile test:...      1
155118  U.S. sees China in 'retrenchment' on move towa...      1
155119  Fifty percent of Speaker Gingrichs tax plan go...      1
155120  Islamic State claims responsibility for attack...      1

[155121 rows x 2 columns]

In [4]:
label_counts = df['label'].value_counts()

print("Different labels and their total numbers:")
for label, count in label_counts.items():
    print(f"Label: {label}, Count: {count}")

Different labels and their total numbers:
Label: 2, Count: 80409
Label: 1, Count: 43372
Label: 0, Count: 31340

In [5]:
# Check for null values in the DataFrame
null_counts = df.isnull().sum()
print("Null Value Counts:")
print(null_counts)

Null Value Counts:
title    0
label    0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

# Separate features and target variable
X = df['title']
y = df['label']

# Stratify the data split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# Combine the features and target variable for training and validation sets
train_df = pd.concat([X_train, y_train], axis=1)
val_df = pd.concat([X_val, y_val], axis=1)

print('trainset size:', train_df.shape)
print('valset size:', val_df.shape)
print('trainset label distribution:', train_df['label'].value_counts())
print('valset label distribution:', val_df['label'].value_counts())

trainset size: (124096, 2)
valset size: (31025, 2)
trainset label distribution: label
2    64327
1    34697
0    25072
Name: count, dtype: int64
valset label distribution: label
2    16082
1     8675
0     6268
Name: count, dtype: int64

In [7]:
# Save the training DataFrame as train.tsv
train_df.to_csv('/content/drive/My Drive/dataset/train.tsv', sep='\t', index=False)
# Save the validation DataFrame as val.tsv
val_df.to_csv('/content/drive/My Drive/dataset/val.tsv', sep='\t', index=False)